version: '3'
services:

  postgres:
    image: postgres:9.5.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password

  node:
    build:
      context: .
      dockerfile: Dockerfile.answers-api
    ports:
      - "3002:3002"
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules